builder/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static_pages#help'

  get 'release_merge/index'

  get 'release_merge/new'

  get 'password_resets/new'
  get 'password_resets/edit'
  get 'articles/index'
  get 'upload/index'


  get    'help'   => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get     'jenkins' => 'jenkins#index'
  get     'builder' => 'builder#index'
  get     'merge' => 'merge#index'
  get    'dev_helpers' => 'dev_helpers#index'
  get    'release_merge' => 'release_merge#index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'logout'  => 'sessions#destroy'
  delete 'microposts/:id'  => 'microposts#destroy'
  get 'microposts/:id'  => 'microposts#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

#  resources :builder
  resources :articles
#  resources :merge
#  resources :jenkins
  resources :upload

  match '/start',  to: 'builder#new',            via: 'post'
  match '/articles/submit',  to: 'articles#submit',            via: 'post'
  match '/merge/new',  to: 'merge#new',            via: 'post'
  match '/dev_helpers/new',  to: 'dev_helpers#new',            via: 'post'
  match '/release_merge/new',  to: 'release_merge#new',            via: 'post'
  match '/jenkins/new',  to: 'jenkins#new',            via: 'post'
  match '/upload/new', to: 'upload#new', via: 'post'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root  'static_pages#home'
end

builder/app/controllers/builder_controller.rb
# coding: utf-8
require 'rubygems'

$LOAD_PATH << ( Rails.root + 'app/controllers')

class BuilderController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:new]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
                                        :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy]
  def index
  end
#  def mails_format_errors(extra_mails)
#	  extra_mails.split(' ').each { |mail|
#		  name = mail.sub(/@dafy.com/,'')
#		  if not name.match(/^[a-z0-9\.]+$/i) then
#			  return "#{mail} is not correct dafy email"
#		  end
#	  }
#	  return nil
 # end
  def new
	  @author = params[:author]
	  @types = params[:types]
	  @extra_mails = params[:extra_mails]
	  @branch = params[:branch]
	  @riqi = params[:riqi]
	  @trunk = params[:trunk]
	  @task = params[:task]
        
	  result = nil
	  if @trunk.blank? or @branch.blank? then
		  @error = "相对主干路径、分支名不能为空"
#	  elsif mails_format_errors then
#		  @error = "通知邮件收件人格式不正确：" + mails_format_errors(extra_mails)
#	  elsif @types == 'add' and @task.blank?  then
          #		  @error = "请输入工单链接"
	  else
		  result = true
	  end

	  if not result then
		  render 'index'
	  else
		  system  "svn-branchcreate.sh", \
			  "-a", @author, \
			  "-t", @trunk, \
			  "-E", @extra_mails, \
			  "-b", @branch, \
			  "-T", @types, \
			  "-d", @riqi, \
			  "-k", @task
	  end
  end
end

builder/app/helpers/builder_helper.rb
module BuilderHelper
end

builder/app/views/builder/create.html.erb
qsq test

builder/app/views/builder/index.html.erb
<% if @error %>
<div id='error_explanation'> <%= @error%>
</div>
<% end %>

<%= javascript_tag "window.onload = builder_onload" %>

<h1 style="text-align:center">svn branch create</h1>
<form method="post" id="vmlinux" action="/start">
	<label>分支类型</label><br>
	<%= params[:types] = "add" unless params[:type]; nil %>
	<%= radio_button_tag "types", "add", params[:types] == "add" %>新建分支&nbsp;&nbsp;
	<%= radio_button_tag "types", "del", params[:types] == "del" %>关闭分支&nbsp;&nbsp;
	<%= radio_button_tag "types", "aa", params[:types] == "aa" %>分支权限添加&nbsp;&nbsp;
	<%= radio_button_tag "types", "cbb", params[:types] == "cbb" %>新建分支(从分支)&nbsp;&nbsp;
	<%= radio_button_tag "types", "tag", params[:types] == "tag" %>新建tag&nbsp;&nbsp;
	<%= radio_button_tag "types", "pd", params[:types] == "pd" %>预删除分支统计&nbsp;&nbsp;
	<%= radio_button_tag "types", "pl", params[:types] == "pl" %>项目查询&nbsp;&nbsp;
	<%= radio_button_tag "types", "at", params[:types] == "at" %>新增主干&nbsp;&nbsp;
	<%= radio_button_tag "types", "ct", params[:types] == "ct" %>新建主干&nbsp;&nbsp;
	<%= radio_button_tag "types", "st", params[:types] == "st" %>删除ftp_name数据&nbsp;&nbsp;
	<%= radio_button_tag "types", "cl", params[:types] == "cl" %>新建基线&nbsp;&nbsp;<br><br>
	<label>项目主干相对路径:</label><br>
	<%= text_area_tag "trunk", params[:trunk],:class =>"test"  %><br>

	<label>分支名称:</label><br>
	<%= text_area_tag "branch", params[:branch],:class =>"test" %><br>

	<label>权限人员:</label><br>
	<%= text_area_tag "author", params[:author],:class =>"test1" %><br>

	<label>禅道工单:</label><br>
	<%= text_area_tag "task", params[:task],:class =>"test1" %><br>
	
	<label>创建完成后发送通知邮件人员名单(公司邮箱，以空格分隔，可不填)</label><br>
	<%= text_area_tag "extra_mails", params[:extra_mails],:class =>"test1" %><br>

	<label>特殊分支日期(格式参照 20170601 可不填)</label><br>
	<%= text_area_tag "riqi", params[:riqi],:class =>"test1" %><br>
	 <input type="submit" value="Submit">
	 <input name="authenticity_token"
	 	type="hidden"
		value="<%= form_authenticity_token %>"/>

builder/app/views/builder/new.html.erb
<p>Your request has been submitted.</p>
<!--
You can find it at <a href="https://192.168.0.220/svn/tech/Branch/">svn-http</a><br><br> 
<%= params.inspect %></span> 
<p>新创建分支:<%= @branch%></p><br>
<p><继续创建新分支,返回创建</p>
<a href=“http://192.168.0.20:3000/">上一页</a><br><br>
-->
<% if @types == "add" %>
新创建分支:https://192.168.0.220/svn/tech/Branch/<%= @branch%><br>
<% elsif @types == "del" %>
删除分支:https://192.168.0.220/svn/tech/Branch/<%= @branch%><br>
<% elsif @types == "cbb" %>
新创建分支:https://192.168.0.220/svn/tech/Branch/<%= @branch%><br>
<% elsif @types == "cl" %>
新创建基线:https://192.168.0.220/svn/tech/Version/<%= @branch%><br>
<% elsif @types == "ct" %>
新创建主干:https://192.168.0.220/svn/tech/Trunk/<%= @trunk%><br>
<% elsif @types == "pl" %>
请注意收邮件<br>
<% else %>
新添加主干:https://192.168.0.220/svn/tech/Trunk/<%= @trunk%>
<% end %><br>

继续访问: <%= link_to 'Back', builder_url(current_user) %><br><br>
权限添加请访问如下网站(具体权限请联系祁善庆、王扬)<br><br>
<a href="http://192.168.0.220:8001/svnadmin/index.php">svnamdin密码权限修改</a><br><br>